version: '3.8'

services:
  # El servicio de base de datos se deshabilita para usar el existente.
  # db:
  #   image: mysql:8.0
  #   container_name: whaticket-db
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
  #     MYSQL_DATABASE: ${DB_DATABASE}
  #     MYSQL_USER: ${DB_USERNAME}
  #     MYSQL_PASSWORD: ${DB_PASSWORD}
  #   volumes:
  #     - ./mysql_data:/var/lib/mysql
  #   ports:
  #     - 3306:3306
  #   networks:
  #     - whaticket-network

  backend:
    build: ./backend
    container_name: whaticket-backend
    restart: always
    environment:
      DB_HOST: db # Esto lo sobreescribes en las Variables de Entorno de Coolify
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      PORT: ${PROXY_PORT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
    ports:
      - ${PROXY_PORT}:${PROXY_PORT}
    depends_on:
      - redis # Se eliminó la dependencia de 'db'
    networks:
      - whaticket-network

  frontend:
    build: ./frontend
    container_name: whaticket-frontend
    restart: always
    ports:
      - 3000:3000
    environment:
      API_URL: http://backend:${PROXY_PORT}
    depends_on:
      - backend
    networks:
      - whaticket-network

  redis:
    image: redis:6.2-alpine
    container_name: whaticket-redis
    restart: always
    # depends_on: 
    #   - db # Se eliminó la dependencia de 'db'
    networks:
      - whaticket-network

networks:
  whaticket-network:
    driver: bridge
